LEFT_HAND:
- ACTION_NAME: 握拳
  POSITION:
  - 67
  - 151
  - 0
  - 0
  - 0
  - 0
  - 37
- ACTION_NAME: 张开
  POSITION:
  - 255
  - 179
  - 255
  - 255
  - 255
  - 255
  - 83
- ACTION_NAME: BS
  POSITION:
  - 53
  - 179
  - 18
  - 232
  - 3
  - 13
  - 58
- ACTION_NAME: OK
  POSITION:
  - 97
  - 179
  - 133
  - 229
  - 236
  - 238
  - 83
- ACTION_NAME: JD
  POSITION:
  - 211
  - 231
  - 255
  - 0
  - 0
  - 0
  - 83
- ACTION_NAME: 'YES'
  POSITION:
  - 0
  - 179
  - 255
  - 255
  - 0
  - 0
  - 40
- ACTION_NAME: ZQ
  POSITION:
  - 125
  - 170
  - 149
  - 150
  - 0
  - 0
  - 44
- ACTION_NAME: ZK
  POSITION:
  - 255
  - 179
  - 255
  - 255
  - 255
  - 255
  - 83
RIGHT_HAND:
- ACTION_NAME: 张开
  POSITION:
  - 255
  - 179
  - 255
  - 255
  - 255
  - 255
  - 83
- ACTION_NAME: ZQ
  POSITION:
  - 125.0
  - 170.0
  - 149.0
  - 150.0
  - 0.0
  - 0.0
  - 44.0
