#!/bin/bash

# This will list all Com-port devices connected to the system
# This WILL NOT list HID devices.

for filename in /dev/ttyACM*; do

	if  udevadm info -n "$filename" | grep -q "VENDOR_ID=2988"; then
		echo $filename
	fi
done
